name: bookstore
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  firebase_remote_config: ^5.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.0.17
  pinput: ^5.0.1
  shimmer: ^3.0.0
  geolocator: ^14.0.0
  shared_preferences: ^2.5.3
  pretty_dio_logger: ^1.4.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  email_validator: ^3.0.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  flutter_local_notifications: ^19.3.0
  flutter_switch: ^0.3.2
  dots_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Sour Gummy
      fonts:
        - asset: assets/fonts/SourGummy-Regular.ttf
    - family: Nunito Medium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
    - family: Nunito SemiBold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
flutter_intl:
  enabled: true
